title: "AlwaysFree"
description: "List of various websites that are for free!"
url: "https://fiftys7ven.github.io/alwaysfree"
baseurl: "/website"
remote-theme: "https://github.com/pages-themes/midnight"
